### ISSUE TITLE
Website?

### ISSUE THREAD

**Issue by davisn** [liebke/avout#18]
The website appears to be broken.  All I get is a blank page.  The root cause appears to be that avout.io creates a frameset referencing https://leibke.github.io/avout/, which is itself a permanent redirect back to avoit.io.

Any chance this could be fixed?

**Comment by liebke** [comment]
That’s interesting. I don’t know why GitHub is forwarding the page back to network solutions. I was using a simple URL redirect to hit GitHub, but now I’ve changed the DNS A record to point to the addresses Github suggests, which should take 24 hours to take effect. If that doesn’t fix the problem, I’m not sure what to do.

David

**Comment by davisn** [comment]
Looks like that fixed it.  Thanks!

**Comment by charles-dyfis-net** [comment]
Hmm. We've got a redirect loop again, though not necessarily the exact same one. Not sure if this should be reopened, or if a new ticket is appropriate...
